insert into CONTACT_PERSON (ID, SALUTATION, FIRST_NAME, LAST_NAME, PHONE_NUMBER) values (1,'MR', 'Atze', 'Peng', '+495551224');
insert into CONTACT_PERSON (ID, SALUTATION, FIRST_NAME, LAST_NAME, PHONE_NUMBER) values (2,'MRS', 'Inge', 'Knall', '+495551225');
insert into CONTACT_PERSON (ID, SALUTATION, FIRST_NAME, LAST_NAME, PHONE_NUMBER) values (3,'MR', 'Peter', 'Pow', '+495553324');